[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "minor_utils"
version = "0.1.1"
description = "Utils compilation for easier work"
authors = [{name = "CyberAxolotl", email = "minor.gleb@outlook.com"}]
license = "MIT"
requires-python = ">=3.10"
readme = "README.md"